<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="generator" content="rustdoc"><meta name="description" content="Invokes a closure, capturing the cause of an unwinding panic if one occurs."><title>catch_unwind in std::panic - Rust</title><script>if(window.location.protocol!=="file:")document.head.insertAdjacentHTML("beforeend","SourceSerif4-Regular-46f98efaafac5295.ttf.woff2,FiraSans-Regular-018c141bf0843ffd.woff2,FiraSans-Medium-8f9a781e4970d388.woff2,SourceCodePro-Regular-562dcc5011b6de7d.ttf.woff2,SourceCodePro-Semibold-d899c5a5c4aeb14a.ttf.woff2".split(",").map(f=>`<link rel="preload" as="font" type="font/woff2" crossorigin href="../../static.files/${f}">`).join(""))</script><link rel="stylesheet" href="../../static.files/normalize-76eba96aa4d2e634.css"><link rel="stylesheet" href="../../static.files/rustdoc-95b3f4a06c1eda6f.css"><meta name="rustdoc-vars" data-root-path="../../" data-static-root-path="../../static.files/" data-current-crate="std" data-themes="" data-resource-suffix="1.83.0" data-rustdoc-version="1.83.0-dev" data-channel="nightly" data-search-js="search-e056c65ede92db13.js" data-settings-js="settings-805db61a62df4bd2.js" ><script src="../../static.files/storage-1d39b6787ed640ff.js"></script><script defer src="sidebar-items1.83.0.js"></script><script defer src="../../static.files/main-419ba87c09f83b8f.js"></script><noscript><link rel="stylesheet" href="../../static.files/noscript-0111fcff984fae8f.css"></noscript><link rel="alternate icon" type="image/png" href="../../static.files/favicon-32x32-422f7d1d52889060.png"><link rel="icon" type="image/svg+xml" href="../../static.files/favicon-2c020d218678b618.svg"></head><body class="rustdoc fn"><!--[if lte IE 11]><div class="warning">This old browser is unsupported and will most likely display funky things.</div><![endif]--><nav class="mobile-topbar"><button class="sidebar-menu-toggle" title="show sidebar"></button><a class="logo-container" href="../../std/index.html"><img class="rust-logo" src="../../static.files/rust-logo-151179464ae7ed46.svg" alt=""></a></nav><nav class="sidebar"><div class="sidebar-crate"><a class="logo-container" href="../../std/index.html"><img class="rust-logo" src="../../static.files/rust-logo-151179464ae7ed46.svg" alt="logo"></a><h2><a href="../../std/index.html">std</a><span class="version">1.83.0-dev</span></h2></div><div class="sidebar-elems"><section id="rustdoc-toc"><h2 class="location"><a href="#">catch_<wbr>unwind</a></h2><h3><a href="#">Sections</a></h3><ul class="block top-toc"><li><a href="#notes" title="Notes">Notes</a></li><li><a href="#examples" title="Examples">Examples</a></li></ul></section><div id="rustdoc-modnav"><h2><a href="index.html">In std::<wbr>panic</a></h2></div></div></nav><div class="sidebar-resizer"></div><main><div class="width-limiter"><rustdoc-search></rustdoc-search><section id="main-content" class="content"><div class="main-heading"><span class="rustdoc-breadcrumbs"><a href="../index.html">std</a>::<wbr><a href="index.html">panic</a></span><h1>Function <span class="fn">catch_unwind</span><button id="copy-path" title="Copy item path to clipboard">Copy item path</button></h1><rustdoc-toolbar></rustdoc-toolbar>
    <span class="sub-heading"><span class="since" title="Stable since Rust version 1.9.0">1.9.0</span> · <a class="src" href="../../src/std/panic.rs.html#344-346">source</a> </span>
</div><pre class="rust item-decl"><code>pub fn catch_unwind&lt;F: <a class="trait" href="../ops/trait.FnOnce.html" title="trait std::ops::FnOnce">FnOnce</a>() -&gt; R + <a class="trait" href="trait.UnwindSafe.html" title="trait std::panic::UnwindSafe">UnwindSafe</a>, R&gt;(f: F) -&gt; <a class="type" href="../thread/type.Result.html" title="type std::thread::Result">Result</a>&lt;R&gt;</code></pre><details class="toggle top-doc" open><summary class="hideme"><span>Expand description</span></summary><div class="docblock"><p>Invokes a closure, capturing the cause of an unwinding panic if one occurs.</p>
<p>This function will return <code>Ok</code> with the closure’s result if the closure
does not panic, and will return <code>Err(cause)</code> if the closure panics. The
<code>cause</code> returned is the object with which panic was originally invoked.</p>
<p>It is currently undefined behavior to unwind from Rust code into foreign
code, so this function is particularly useful when Rust is called from
another language (normally C). This can run arbitrary Rust code, capturing a
panic and allowing a graceful handling of the error.</p>
<p>It is <strong>not</strong> recommended to use this function for a general try/catch
mechanism. The <a href="../thread/type.Result.html" title="type std::thread::Result"><code>Result</code></a> type is more appropriate to use for functions that
can fail on a regular basis. Additionally, this function is not guaranteed
to catch all panics, see the “Notes” section below.</p>
<p>The closure provided is required to adhere to the <a href="trait.UnwindSafe.html" title="trait std::panic::UnwindSafe"><code>UnwindSafe</code></a> trait to ensure
that all captured variables are safe to cross this boundary. The purpose of
this bound is to encode the concept of <a href="https://github.com/rust-lang/rfcs/blob/master/text/1236-stabilize-catch-panic.md">exception safety</a> in the type
system. Most usage of this function should not need to worry about this
bound as programs are naturally unwind safe without <code>unsafe</code> code. If it
becomes a problem the <a href="struct.AssertUnwindSafe.html" title="struct std::panic::AssertUnwindSafe"><code>AssertUnwindSafe</code></a> wrapper struct can be used to quickly
assert that the usage here is indeed unwind safe.</p>
<h2 id="notes"><a class="doc-anchor" href="#notes">§</a>Notes</h2>
<p>Note that this function <strong>might not catch all panics</strong> in Rust. A panic in
Rust is not always implemented via unwinding, but can be implemented by
aborting the process as well. This function <em>only</em> catches unwinding panics,
not those that abort the process.</p>
<p>Note that if a custom panic hook has been set, it will be invoked before
the panic is caught, before unwinding.</p>
<p>Also note that unwinding into Rust code with a foreign exception (e.g.
an exception thrown from C++ code) is undefined behavior.</p>
<p>Finally, be <strong>careful in how you drop the result of this function</strong>.
If it is <code>Err</code>, it contains the panic payload, and dropping that may in turn panic!</p>
<h2 id="examples"><a class="doc-anchor" href="#examples">§</a>Examples</h2>
<div class="example-wrap"><pre class="rust rust-example-rendered"><code><span class="kw">use </span>std::panic;

<span class="kw">let </span>result = panic::catch_unwind(|| {
    <span class="macro">println!</span>(<span class="string">"hello!"</span>);
});
<span class="macro">assert!</span>(result.is_ok());

<span class="kw">let </span>result = panic::catch_unwind(|| {
    <span class="macro">panic!</span>(<span class="string">"oh no!"</span>);
});
<span class="macro">assert!</span>(result.is_err());</code></pre><a class="test-arrow" target="_blank" title="Run code" href="https://play.rust-lang.org/?code=%23!%5Ballow(unused)%5D%0Afn+main()+%7B%0A++++use+std::panic;%0A++++%0A++++let+result+=+panic::catch_unwind(%7C%7C+%7B%0A++++++++println!(%22hello!%22);%0A++++%7D);%0A++++assert!(result.is_ok());%0A++++%0A++++let+result+=+panic::catch_unwind(%7C%7C+%7B%0A++++++++panic!(%22oh+no!%22);%0A++++%7D);%0A++++assert!(result.is_err());%0A%7D&amp;edition=2021"></a></div>
</div></details></section></div></main></body></html>